name: Linux build
on:
  - pull_request
  - push
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CXXFLAGS: -std=${{ matrix.standard }}
      TEST_BUILD_MODULES: 
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update --assume-yes
          sudo apt-get install --assume-yes --no-install-recommends librocksdb-dev g++ git make libc++-dev libc++abi-dev pkg-config
      - name: Run build
        run: ./make/build ${{ matrix.compiler }}
      - name: Check version
        run: ./run/beryldb version      
    strategy:
      matrix:
        compiler:
          - g++-10
        standard:
          - c++14
          - c++17
          - c++2a          

